### ISSUE TITLE
Multiple providers requires multiple mock services

### ISSUE THREAD

**Issue by matiasanaya** [pact-foundation/karma-pact#1]
Hi, I'm trying to test against multiple providers. There is an issue if done within the same mock services, as explained in [pact-foundation/pact-mock_service/issues/39](https://github.com/pact-foundation/pact-mock_service/issues/39).

Is there a way to run multiple mock services (one per provider) from Karma?

**Comment by BenDave** [comment]
Note that this issue is fixed by the following PR: https://github.com/pact-foundation/karma-pact/pull/4

**Comment by mboudreau** [comment]
@matiasanaya Can I ask what you're trying to accomplish?  I'm just trying to understand your requirement and situation so that we can make a more informed decision as to the best approach.  Cheers.

**Comment by matiasanaya** [comment]
@mboudreau I need to test code against two different providers, which calls to are intertwined. I'd like to keep the pact files for those two providers separate since I'd like to publish them to a broker so that either provider can be validated independently.

Just re-read the original issue I referenced and it mentions that _If you give the consumer and provider names in the POST /pact call rather than at startup, it will use them to write the pact_. That sounds like a valid solution, though I'm not entirely sure if I tried it back then or if it had limitations that didn't work for me.

@BenDave solution seems to be along the lines of what I had in mind when I created this issue.

**Comment by mboudreau** [comment]
@matiasanaya Thanks for that.  I'm currently in talks with @BenDave to fix the PR to allow this functionality in a way I think would be more appropriate.  Please review my proposed solution in the PR.

**Comment by mboudreau** [comment]
@matiasanaya @BenDave version 1.0.0 has been deployed.  Please try it and get back to me.  The name of the package changes to reflect our standard across pact-foundation to use a scope, so please do `npm install @pact-foundation/karma-pact --save-dev` and remove the old karma-pact as it is now deprecated.

@tarciosaraiva Could you please deprecate karma-pact that's under your name?  Thanks.

**Comment by tarciosaraiva** [comment]
it's done @mboudreau. This is what the users will get now:

```
$ npm i karma-pact
npm WARN deprecated karma-pact@0.0.7: karma-pact has been deprecated in favor of @pact-foundation/karma-pact. Please update your package.json.
```

**Comment by BenDave** [comment]
@mboudreau v1.0.0 successfully passed my tests. Well done ...

**Comment by mefellows** [comment]
Great to hear! Thanks for your patience 🤘
