### ISSUE TITLE
NPM Install fails when version of Node is > 10.0

### ISSUE THREAD

**Issue by Sikenyon** [pact-foundation/karma-pact#14]
As per https://github.com/abbr/deasync/issues/97, if the version of Node installed locally is > V10.0 then npm install fails due to an issue within Deasync itself. Deasync has been updated to the latest version (0.1.13) which fixes this issue, but karma-pact still references the old broken version (0.1.12).

All of our build agents have just been updated to Node V10 so we now cannot run npm build without downgrading the version of Node.

To replicate the issue, update your local version of Node to > V10 and then run npm install on any project that uses karma-pact.

**Comment by mefellows** [comment]
Can you please check this has been fixed with the latest release? We'll get a node v10 build out soon also

**Comment by Barvor** [comment]
does not seem to work. 
`    "@pact-foundation/karma-pact": "^2.1.8", `

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Markus-Ende** [comment]
same here, could you update deasync dependency to 0.1.13? That should fix it...

**Comment by mefellows** [comment]
OK have updated to latest version of deasync, and `v2.1.9` of `karma-pact` should be on its way.
