### ISSUE TITLE
Unexplained race condition

### ISSUE THREAD

**Issue by hmil** [pact-foundation/karma-pact#19]
Hi, I'm looking for an explanation about the ugly [`setTimeout`-based workaround](https://github.com/pact-foundation/pact-js/blob/master/examples/karma/jasmine/client-spec.js#L11) featured in the official example usage of karma-pact.

Obviously, you want your tests deterministic and hence this kind of arbitrary waits must be eliminated. I dug around and found that the hack was introduced by @tarciosaraiva in 2016 when he [included the karma test in the build pipeline](https://github.com/pact-foundation/pact-js/commit/a60d1d3c17609e0b49665d965634b0f18260446d#diff-ccbcdd7cd10cc7a6c2cc2b9e50973d96R11). However, the commit doesn't explain exactly why this workaround was needed in the first place.

The source of karma-pact seems to handle initialization just fine. As in: if the promise provided by `pact-node` in the return from `start()` only resolves after the server has been started, then karma-pact should be free from race conditions. So, is it that pact-node resolves the promise early, leaving a small window open for code to run before the server is actually up?
Here again, I looked at the source of `pact-node` and it looks like it does the right thing and probes the server with HTTP requests until success before resolving the promise.

After some more investigation, there was [a commit in karma-pact in 2017](https://github.com/pact-foundation/karma-pact/commit/b705182b2c931bea2e5917d860f57a4b90752026) which changed from returning a promise to synchronously waiting for the completion of said promise.
Maybe this is what the above mentioned workaround was working around. But now that it has been fixed, there should be no reason to have this timeout anymore, should there?

**Comment by fernanfs** [comment]
It has been a while since you've created that issue. But recently I faced multiple problems with `karma-pact`. It has now been updated to a more recent version of `pact-node` and to the async framework support of `karma`. When using any `karma` version newer than 5.x, that kind of workaround should not be necessary anymore.

**Comment by fernanfs** [comment]
What was missing in my comment: could you give karma-pact@v3.1.0 a shot?
