### ISSUE TITLE
Feature: Publishing Pacts

### ISSUE THREAD

**Issue by niklas-wortmann** [pact-foundation/karma-pact#7]
I think for testing frontend application it shouldn't be necessary to use grunt or gulp or something like that.  Wouldn't it be great to automatically publish the pacts after the tests to the pact broker or any other kind of repository? Maybe this is possible by adding a karma reporter.

What do you think of this?

**Comment by nbrink91** [comment]
@JWO719, I made a small Karma reporter to accomplish this. See [@mattersight/karma-pact-reporter](https://www.npmjs.com/package/@mattersight/karma-pact-reporter). This is basically just a wrapper around pact-node to report the Pact file.

**Comment by niklas-wortmann** [comment]
Ok Good to know. I will take a look at it and report :smiley:

**Comment by mboudreau** [comment]
@JWO719 Sorry, this completely flew under my radar, December was hectic for me.  I'll see what can be done about this, I think you bring a valid point.

**Comment by niklas-wortmann** [comment]
@mboudreau definitely no problem. When there is any way I can help you, just inform me. Thank you!

**Comment by niklas-wortmann** [comment]
@nbrink91 your solution looks quite good I think. @mboudreau maybe it makes sense to integrate it in the plugin?

**Comment by mboudreau** [comment]
Yep, I'll be looking into this when I have a sec.  I have a few fires to
put out at the moment :/
